import type { Product } from "@/lib/cart-store"

export const products: Product[] = [
  {
    id: "1",
    name: "Minimal Leather Tote",
    price: 189,
    originalPrice: 249,
    image: "/luxury-minimal-leather-tote-bag-beige.jpg",
    category: "Bags",
    description:
      "Crafted from premium full-grain leather, this minimalist tote features clean lines and thoughtful details. Perfect for everyday elegance.",
    rating: 4.9,
    reviews: 128,
    sizes: ["S", "M", "L"],
    colors: ["Beige", "Black", "Tan"],
    inStock: true,
    featured: true,
  },
  {
    id: "2",
    name: "Cashmere Crew Sweater",
    price: 295,
    image: "/luxury-cashmere-cream-sweater-minimalist.jpg",
    category: "Clothing",
    description:
      "Ultra-soft 100% Mongolian cashmere sweater with a relaxed fit. Timeless design meets exceptional comfort.",
    rating: 4.8,
    reviews: 89,
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Cream", "Charcoal", "Navy"],
    inStock: true,
    featured: true,
  },
  {
    id: "3",
    name: "Ceramic Table Lamp",
    price: 320,
    originalPrice: 380,
    image: "/modern-ceramic-table-lamp-minimalist-white.jpg",
    category: "Home",
    description:
      "Handcrafted ceramic lamp with organic curves and a linen shade. Creates warm, ambient lighting for any space.",
    rating: 4.7,
    reviews: 56,
    inStock: true,
    featured: true,
  },
  {
    id: "4",
    name: "Merino Wool Scarf",
    price: 125,
    image: "/luxury-merino-wool-scarf-camel-color.jpg",
    category: "Accessories",
    description: "Lightweight yet warm merino wool scarf. The perfect finishing touch for transitional weather.",
    rating: 4.9,
    reviews: 203,
    colors: ["Camel", "Grey", "Black"],
    inStock: true,
  },
  {
    id: "5",
    name: "Leather Card Holder",
    price: 75,
    image: "/minimalist-leather-card-holder-wallet-black.jpg",
    category: "Accessories",
    description: "Slim leather card holder with four card slots and a center pocket. Elegant simplicity.",
    rating: 4.6,
    reviews: 312,
    colors: ["Black", "Brown", "Navy"],
    inStock: true,
  },
  {
    id: "6",
    name: "Linen Blend Blazer",
    price: 425,
    originalPrice: 495,
    image: "/modern-linen-blazer-jacket-oatmeal-color.jpg",
    category: "Clothing",
    description: "Relaxed-fit blazer in breathable linen blend. Effortlessly elevated for work or weekend.",
    rating: 4.8,
    reviews: 67,
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Oatmeal", "Navy", "Olive"],
    inStock: true,
    featured: true,
  },
  {
    id: "7",
    name: "Handwoven Throw Blanket",
    price: 245,
    image: "/luxury-handwoven-throw-blanket-neutral-tones.jpg",
    category: "Home",
    description: "Artisan-woven throw in soft cotton blend. Each piece is unique with subtle textural variations.",
    rating: 4.9,
    reviews: 94,
    colors: ["Natural", "Charcoal", "Terracotta"],
    inStock: true,
  },
  {
    id: "8",
    name: "Silk Sleep Set",
    price: 350,
    image: "/luxury-silk-pajama-set-champagne-color.jpg",
    category: "Clothing",
    description:
      "22-momme mulberry silk pajama set. The ultimate in sleep luxury with temperature-regulating properties.",
    rating: 4.7,
    reviews: 156,
    sizes: ["XS", "S", "M", "L"],
    colors: ["Champagne", "Midnight", "Blush"],
    inStock: true,
  },
  {
    id: "9",
    name: "Geometric Vase",
    price: 165,
    image: "/modern-geometric-ceramic-vase-white-minimalist.jpg",
    category: "Home",
    description:
      "Sculptural ceramic vase with geometric angles. A striking accent piece that stands alone or with stems.",
    rating: 4.5,
    reviews: 43,
    inStock: true,
  },
  {
    id: "10",
    name: "Suede Loafers",
    price: 285,
    originalPrice: 340,
    image: "/luxury-suede-loafers-shoes-taupe.jpg",
    category: "Shoes",
    description: "Italian suede loafers with leather sole. Classic silhouette with modern comfort.",
    rating: 4.8,
    reviews: 178,
    sizes: ["6", "7", "8", "9", "10", "11", "12"],
    colors: ["Taupe", "Black", "Burgundy"],
    inStock: true,
  },
  {
    id: "11",
    name: "Cotton Canvas Crossbody",
    price: 145,
    image: "/minimal-canvas-crossbody-bag-sage-green.jpg",
    category: "Bags",
    description: "Water-resistant cotton canvas with leather trim. Lightweight and perfect for hands-free style.",
    rating: 4.6,
    reviews: 89,
    colors: ["Sage", "Stone", "Black"],
    inStock: true,
  },
  {
    id: "12",
    name: "Porcelain Dinnerware Set",
    price: 495,
    image: "/minimal-porcelain-dinnerware-set-white-modern.jpg",
    category: "Home",
    description: "16-piece porcelain set with matte glaze. Clean lines for the modern table setting.",
    rating: 4.9,
    reviews: 67,
    inStock: true,
    featured: true,
  },
]

export const categories = [
  { name: "All", slug: "all" },
  { name: "Clothing", slug: "clothing" },
  { name: "Bags", slug: "bags" },
  { name: "Accessories", slug: "accessories" },
  { name: "Home", slug: "home" },
  { name: "Shoes", slug: "shoes" },
]

export const featuredProducts = products.filter((p) => p.featured)
